import re
import plotly.express as px
import streamlit as st

from utils.data_loader import load_data
from agent.llm_client import chat_completion, is_configured
from utils.theme import load_css, section_header, metric_card, style_fig, threat_badge, CYAN, AMBER, RED, GREEN

st.set_page_config(
    page_title="AI Intelligence Report",
    page_icon="🧠",
    layout="wide"
)
load_css()

st.title("🧠 AI Intelligence Report")

st.markdown("""
Generate an AI-assisted intelligence summary from the
Global Terrorism Database (GTD).
""")

df = load_data()

# -------------------------------------------------
# Sidebar Filters
# -------------------------------------------------

st.sidebar.markdown("### 🎛️ Report Filters")

years = sorted(df["iyear"].unique())

selected_year = st.sidebar.selectbox("Select Year", ["All"] + list(years))

if selected_year != "All":
    df = df[df["iyear"] == selected_year]

# -------------------------------------------------
# Key Statistics
# -------------------------------------------------

total_incidents = len(df)
total_killed = int(df["nkill"].fillna(0).sum())
total_wounded = int(df["nwound"].fillna(0).sum())
countries = df["country_txt"].nunique()

top_countries = df["country_txt"].value_counts().head(10)
top_groups = df["gname"].value_counts().head(10)
attack_types = df["attacktype1_txt"].value_counts()
weapon_types = df["weaptype1_txt"].value_counts()

avg_killed = df["nkill"].fillna(0).mean()

if avg_killed < 2:
    threat = "LOW 🟢"
    threat_level_plain = "LOW"
elif avg_killed < 5:
    threat = "MEDIUM 🟡"
    threat_level_plain = "MEDIUM"
else:
    threat = "HIGH 🔴"
    threat_level_plain = "HIGH"

# -------------------------------------------------
# Dashboard Metrics
# -------------------------------------------------

section_header("Key Intelligence Indicators", "📊")

col1, col2, col3, col4 = st.columns(4)
with col1:
    metric_card("Incidents", f"{total_incidents:,}", icon="💥", color=CYAN)
with col2:
    metric_card("Fatalities", f"{total_killed:,}", icon="☠️", color=RED)
with col3:
    metric_card("Injuries", f"{total_wounded:,}", icon="🏥", color=AMBER)
with col4:
    st.markdown(
        f"""<div class="metric-card">
        <div class="accent-bar" style="background:{GREEN};"></div>
        <div class="metric-icon">🚦</div>
        <div class="metric-value">{threat_badge(threat_level_plain)}</div>
        <div class="metric-label">Threat Level</div>
        </div>""",
        unsafe_allow_html=True,
    )

# -------------------------------------------------
# Executive Summary  (LLM-generated if configured, else templated fallback)
# -------------------------------------------------

st.markdown("<br>", unsafe_allow_html=True)
section_header("Executive Summary", "🗞️")

facts = {
    "total_incidents": total_incidents,
    "countries": countries,
    "total_killed": total_killed,
    "total_wounded": total_wounded,
    "threat_level": threat,
    "top_country": top_countries.index[0] if len(top_countries) else "N/A",
    "top_group": top_groups.index[0] if len(top_groups) else "N/A",
    "top_attack_type": attack_types.index[0] if len(attack_types) else "N/A",
    "top_weapon": weapon_types.index[0] if len(weapon_types) else "N/A",
    "year_filter": selected_year,
}


def templated_summary(f: dict) -> str:
    return f"""
During the selected period ({f['year_filter']}), {f['total_incidents']:,} terrorist incidents
were recorded across {f['countries']} countries.

The attacks resulted in {f['total_killed']:,} fatalities and {f['total_wounded']:,} injuries.

The overall threat level is assessed as {f['threat_level']}.

The most affected country is {f['top_country']}.
The most active terrorist organization is {f['top_group']}.
The most common attack type is {f['top_attack_type']}.
The most frequently used weapon is {f['top_weapon']}.
"""


def templated_recommendations(f: dict) -> str:
    return f"""
1. Increase surveillance in {f['top_country']}.
2. Closely monitor activities associated with {f['top_group']}.
3. Strengthen protection of infrastructure that is frequently targeted.
4. Enhance intelligence sharing among agencies.
5. Increase monitoring of {f['top_attack_type'].lower()} incidents.
6. Continue trend analysis using predictive machine learning models.
"""


use_llm = is_configured()

if use_llm:
    st.caption("✨ Generated by an LLM via OpenRouter, grounded in the stats above.")
else:
    st.caption("ℹ️ Showing a templated summary. Add an OpenRouter API key (see `.env.example`) to enable LLM-generated analysis.")

if use_llm:
    with st.spinner("Generating AI intelligence summary..."):
        try:
            prompt = f"""You are a military intelligence analyst. Using ONLY the
following factual statistics (do not invent numbers), write:
1) A 3-4 sentence executive summary of the situation.
2) 4-6 specific, non-generic recommendations tied to the actual top country,
   group, attack type and weapon type given.

Facts:
{facts}

Format your response as:
SUMMARY:
<summary text>

RECOMMENDATIONS:
<numbered list>
"""
            llm_output = chat_completion(
                messages=[
                    {"role": "system", "content": "You are a concise, factual military intelligence analyst."},
                    {"role": "user", "content": prompt},
                ]
            )
            if "RECOMMENDATIONS:" in llm_output:
                summary, recommendation = llm_output.split("RECOMMENDATIONS:", 1)
                summary = summary.replace("SUMMARY:", "").strip()
                recommendation = recommendation.strip()
            else:
                summary = llm_output.strip()
                recommendation = templated_recommendations(facts)
        except Exception as e:
            st.warning(f"LLM generation failed ({e}). Falling back to templated summary.")
            summary = templated_summary(facts)
            recommendation = templated_recommendations(facts)
else:
    summary = templated_summary(facts)
    recommendation = templated_recommendations(facts)

# ---------------------------------------------------
# Executive summary rendered as a memo/report card
# ---------------------------------------------------
summary_body = summary.strip().replace("\n\n", "<br><br>").replace("\n", " ")

st.markdown(
    f"""
    <div class="content-card" style="border-left:3px solid {CYAN};">
        <div style="display:flex; justify-content:space-between; align-items:center;
                    font-family:'JetBrains Mono', monospace; font-size:0.7rem;
                    color:#7C8798; letter-spacing:1px; text-transform:uppercase; margin-bottom:14px;">
            <span>Memo · Executive Summary</span>
            <span>Scope: {selected_year}</span>
        </div>
        <div style="color:#E8ECF1; font-size:0.95rem; line-height:1.7;">
            {summary_body}
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

# -------------------------------------------------
# Top Countries / Groups charts — recolored
# -------------------------------------------------

st.markdown("<br>", unsafe_allow_html=True)
section_header("Top 10 High-Risk Countries", "🌍")
fig = px.bar(top_countries, x=top_countries.values, y=top_countries.index,
             orientation="h", labels={"x": "Incidents", "y": "Country"},
             color_discrete_sequence=[CYAN])
fig = style_fig(fig, height=400)
st.markdown('<div class="content-card">', unsafe_allow_html=True)
st.plotly_chart(fig, use_container_width=True)
st.markdown('</div>', unsafe_allow_html=True)

section_header("Most Active Terrorist Groups", "👥")
fig2 = px.bar(top_groups, x=top_groups.values, y=top_groups.index,
              orientation="h", labels={"x": "Attacks", "y": "Group"},
              color_discrete_sequence=[RED])
fig2 = style_fig(fig2, height=400)
st.markdown('<div class="content-card">', unsafe_allow_html=True)
st.plotly_chart(fig2, use_container_width=True)
st.markdown('</div>', unsafe_allow_html=True)

# -------------------------------------------------
# AI Intelligence Assessment — numbered ops list
# -------------------------------------------------

section_header("AI Intelligence Assessment", "🛡️")

# Parse "1. ..." / "2. ..." style lines out of the recommendation text
# (works for both the templated fallback and typical LLM numbered output).
items = []
for line in recommendation.strip().splitlines():
    line = line.strip()
    if not line:
        continue
    m = re.match(r"^\d+[\.\)]\s*(.+)", line)
    items.append(m.group(1) if m else line)

if not items:
    items = [recommendation.strip()]

ops_html = ""
for i, item in enumerate(items, start=1):
    ops_html += f"""
    <div style="display:flex; gap:14px; align-items:flex-start; padding:10px 0;
                border-bottom:1px solid rgba(255,255,255,0.06);">
        <div style="font-family:'JetBrains Mono', monospace; color:{AMBER}; font-weight:700;
                    min-width:28px;">{i:02d}</div>
        <div style="color:#E8ECF1; font-size:0.92rem; line-height:1.5;">{item}</div>
    </div>
    """

st.markdown(
    f"""
    <div class="content-card" style="border-left:3px solid {AMBER};">
        <div style="font-family:'JetBrains Mono', monospace; font-size:0.7rem;
                    color:#7C8798; letter-spacing:1px; text-transform:uppercase; margin-bottom:6px;">
            Operational Recommendations
        </div>
        {ops_html}
    </div>
    """,
    unsafe_allow_html=True,
)

# -------------------------------------------------
# Download Report
# -------------------------------------------------

report = f"""
==============================
AI INTELLIGENCE REPORT
==============================

Total Incidents : {total_incidents}
Fatalities : {total_killed}
Injuries : {total_wounded}
Threat Level : {threat}

Top Country : {facts['top_country']}
Top Group : {facts['top_group']}
Most Common Attack : {facts['top_attack_type']}
Most Common Weapon : {facts['top_weapon']}

Executive Summary
{summary}

Recommendations
{recommendation}
"""

st.download_button(
    "📄 Download Intelligence Report",
    report,
    file_name="AI_Intelligence_Report.txt"
)
